blank_issues_enabled: true
contact_links:
  - name: Questions and Discussion
    url: https://discuss.pytorch.org/
    about: Ask questions and discuss with other PyTorch community members. Please use the 'data' category.